# ENV["SINATRA_ENV"] ||= "development"
require_relative './config/environment'
require 'sinatra/activerecord/rake'


ActiveRecord::Base.logger = Logger.new(STDOUT)

desc "Start our app console"
task :console do
  Pry.start
end
